INFO     HTTP_CLIENT:event_hooks.py:29 Make POST request to http://localhost:8000/api/v1/users
INFO     HTTP_CLIENT:event_hooks.py:39 Got response 200 OK from http://localhost:8000/api/v1/users
INFO     HTTP_CLIENT:event_hooks.py:29 Make POST request to http://localhost:8000/api/v1/authentication/login
INFO     HTTP_CLIENT:event_hooks.py:39 Got response 200 OK from http://localhost:8000/api/v1/authentication/login
INFO     HTTP_CLIENT:event_hooks.py:29 Make GET request to http://localhost:8000/api/v1/files/incorrect-file-id
INFO     HTTP_CLIENT:event_hooks.py:39 Got response 422 Unprocessable Entity from http://localhost:8000/api/v1/files/incorrect-file-id
INFO     BASE_ASSERTIONS:base.py:11 Проверка статуса кода ответа 422
INFO     FILES_ASSERTIONS:files.py:78 Проверка ответа на получения файла с некорректным айди
INFO     ERRORS_ASSERTIONS:errors.py:23 Проверка валидационной ошибки
INFO     BASE_ASSERTIONS:base.py:37 Проверка что длина details эквивалентна 1
INFO     ERRORS_ASSERTIONS:errors.py:11 Проверка валидационной ошибки
INFO     BASE_ASSERTIONS:base.py:16 Проверка что type эквивалентна uuid_parsing
INFO     BASE_ASSERTIONS:base.py:16 Проверка что input эквивалентна incorrect-file-id
INFO     BASE_ASSERTIONS:base.py:16 Проверка что context эквивалентна {'error': 'invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `i` at 1'}
INFO     BASE_ASSERTIONS:base.py:16 Проверка что message эквивалентна Input should be a valid UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `i` at 1
INFO     BASE_ASSERTIONS:base.py:16 Проверка что location эквивалентна ['path', 'file_id']
INFO     SCHEMA_ASSERTIONS:schema.py:18 Validating JSON schema